language: swift
os: osx
osx_image: xcode10.1
xcode_project: SwiftPath.xcodeproj
xcode_scheme: "SwiftPath iOS"
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone 8

language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
