language: swift
os: osx
osx_image: xcode10.1

env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

language: ruby
rvm:
  - 2.5.0

before_install:
  - gem install bundler
  - gem install xcpretty --no-ri --no-rdoc

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - xcodebuild -project SwiftPath.xcodeproj -scheme "SwiftPath iOS" -configuration Debug -destination "platform=iOS Simulator,OS=11.3,name=iPhone 8" -UseModernBuildSystem=NO clean test | xcpretty --test --color
  #- bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
